### ISSUE TITLE
MEDIUM FIX: Avoid Innermost Exception Validation

### ISSUE THREAD

**Issue by ElbekDeveloper** [The-Standard-Organization/Xeption#62]
# The Problem
We are testing against `SecurityTokenMalformedException` coming from Microsoft.IdentityModel.Tokens namespace. The inner exception of it is throwing the following error while test is running:
```txt
Expected inner exception (level 2) message to be "Value does not fall within the expected range.", but found "IDX12709: CanReadToken() returned false. JWT is not well formed.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EncodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'."
```

# The Ask
I don't want the library to go as deep. How can I ignore the validation after 1 level starting from system exception

**Comment by cjdutoit** [comment]
@ElbekDeveloper,  this is expected behaviour.   Is this for a unit test?  You should be able to setup your expected exception to be thrown by the unit test and then verify that the actual exception match the expected exception.
